export enum FailureType {
    UnexpectedMessage = 1,
    ButtonExpected = 2,
    DataError = 3,
    ActionCancelled = 4,
    PinExpected = 5,
    PinCancelled = 6,
    PinInvalid = 7,
    InvalidSignature = 8,
    ProcessError = 9,
    NotEnoughFunds = 10,
    NotInitialized = 11,
    PinMismatch = 12,
    WipeCodeMismatch = 13,
    FirmwareError = 99,
}

export enum ButtonRequestType {
    Other = 1,
    FeeOverThreshold = 2,
    ConfirmOutput = 3,
    ResetDevice = 4,
    ConfirmWord = 5,
    WipeDevice = 6,
    ProtectCall = 7,
    SignTx = 8,
    FirmwareCheck = 9,
    Address = 10,
    PublicKey = 11,
    MnemonicWordCount = 12,
    MnemonicInput = 13,
    PassphraseType = 14,
    UnknownDerivationPath = 15,
    RecoveryHomepage = 16,
    Success = 17,
    Warning = 18,
    EnterPinOnDevice = 101,
    EnterNewPinOnDevice = 102,
    ReEnterNewPinOnDevice = 103,
    PinOnDeviceDone = 104,
} 